FROM node:boron

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/package.json
COPY src /usr/src/app
RUN cd /usr/src/app
RUN npm install

EXPOSE 8080
CMD [ "npm", "star" ]